# Generated by Django 5.1.2 on 2024-12-20 09:05

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show, 1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(default='defaultpassword', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('vendor', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('extra_image_1', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('extra_image_2', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('extra_image_3', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('quantity', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('description', models.TextField(max_length=3500)),
                ('status', models.BooleanField(default=False, help_text='0-show, 1-Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default, 1-Trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sizes', models.CharField(blank=True, help_text='Available sizes (e.g., S, M, L, XL, XXL, AGE6)', max_length=255, null=True)),
                ('size_format', models.CharField(choices=[('SIZE', 'SIZE'), ('AGE', 'AGE')], help_text='Specify size format: SIZE (e.g., XL) or AGE (e.g., AGE6)', max_length=10)),
                ('format_prefix', models.CharField(default='WSHORTS-2COMBO', help_text='Enter the format prefix (e.g., WSHORTS-2COMBO)', max_length=50)),
                ('feature_1', models.CharField(blank=True, max_length=855, null=True)),
                ('feature_2', models.CharField(blank=True, max_length=855, null=True)),
                ('feature_3', models.CharField(blank=True, max_length=855, null=True)),
                ('feature_4', models.CharField(blank=True, max_length=855, null=True)),
                ('feature_5', models.CharField(blank=True, max_length=855, null=True)),
                ('feature_6', models.CharField(blank=True, max_length=855, null=True)),
                ('feature_7', models.CharField(blank=True, max_length=855, null=True)),
                ('feature_8', models.CharField(blank=True, max_length=855, null=True)),
                ('feature_9', models.CharField(blank=True, max_length=855, null=True)),
                ('feature_10', models.CharField(blank=True, max_length=855, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
                ('address', models.TextField(default='unkown')),
                ('first_name', models.CharField(default='unkown', max_length=100)),
                ('last_name', models.CharField(default='unkown', max_length=100)),
                ('email', models.EmailField(default='unkown', max_length=254)),
                ('phone', models.CharField(default='unkown', max_length=15)),
                ('country', models.CharField(default='unkown', max_length=100)),
                ('city', models.CharField(default='unkown', max_length=100)),
                ('postal_code', models.CharField(default='unkown', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('selected_size', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
