# Generated by Django 5.1.2 on 2024-12-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
