# Generated by Django 5.1.2 on 2024-12-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_orders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(default='unkown', max_length=180),
        ),
    ]
