# Generated by Django 5.1.2 on 2024-12-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders_payment_id_alter_orders_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='razorpay_order_id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='country',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.EmailField(default='unknown', max_length=254),
        ),
        migrations.AlterField(
            model_name='orders',
            name='first_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='last_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='postal_code',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
